### ISSUE TITLE
Means to customize the logo

### ISSUE THREAD

**Issue by dbsanfte** [jenkinsci/theme-manager-plugin#132]
### What feature do you want to see added?

Hiya, 

It was suggested that it would be better to submit a feature request here:

https://github.com/jenkinsci/material-theme-plugin/issues/38

Basically, it would be nice to have a way to customize the logo in the top left corner  of Jenkins without needing to get into CSS hacking.

**Comment by maxnitze** [comment]
There is a workaround to do it right now (just to leave it here):

* additionally install the plugin `simple-theme-plugin` (https://plugins.jenkins.io/simple-theme-plugin)
* use its CSS configuration to
  * replace the Jenkins logo
    ```css
    #jenkins-home-link > img#jenkins-head-icon {
      content: url(...);
    }
    ```
  * optional: hide the "Jenkins" text
    ```css
    #jenkins-home-link > img#jenkins-name-icon {
      display: none !important;
    }
    ```
* in JCasC I have this config, for example
  ```yaml
  unclassified:
    themeManager:
      disableUserThemes: false
      theme: 'darkSystem'
    simple-theme-plugin:
      elements:
        - cssText:
            text: |-
              /* replace logo in header. will probably be added as a feature to the theme-manager plugin (https://github.com/jenkinsci/theme-manager-plugin/issues/132) */
              #jenkins-home-link > img#jenkins-head-icon {
                content: url('data:image/png;base64,<BASE64 ENCODED PNG IMAGE>');
              }
              #jenkins-home-link > img#jenkins-name-icon {
                display: none !important;
              }

  ```
